name: dracula_game
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bonfire: ^2.12.2
  firebase_core: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/draculatiles/maps/
    - assets/images/draculatiles/tilesets/
    - assets/images/draculatiles/items/
    - assets/images/draculatiles/RF_Catacombs_v1.0/
    - assets/images/draculascastletiles/
    - assets/images/draculascastletiles/map/
    - assets/images/draculascastletiles/tiles/
    - assets/images/player/